name: Discord_Azure_TTS_Bot

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
        
    - name: Install dependencies
      run: |
        . (Join-Path $env:USERPROFILE "PycharmProjects/Discord_Azure_TTS_Bot/venv39/Scripts/activate.ps1")
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Run application
      run: |
        nssm set Discord_Azure_TTS_Bot AppEnvironmentExtra AZURE_TTS_TOKEN=${{secrets.AZURE_TTS_TOKEN}} BOT_TOKEN=${{secrets.BOT_TOKEN}} OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
        nssm restart Discord_Azure_TTS_Bot
